version: '3.8'

services:
  web:
    restart: always
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=01ec&3@)b0$$-302i(m$$e+b^5h3gu96ffg%&bmv-=e5qt(p0w!!"
      - "DJANGO_DEBUG=True"
  front:
    build: ./vue_spa
    ports:
      - 8080:8080
    volumes:
      - .:/vue_spa
  db:
    restart: always
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

